[program:xorg]
command=/usr/bin/Xorg :99 -config /etc/X11/xorg.conf -noreset -nolisten tcp
priority=100
autorestart=true
stdout_logfile=/var/log/desk/xorg.log
redirect_stderr=true

[program:xfce]
environment=HOME="/home/zaza",USER="zaza",DISPLAY=":99",XDG_RUNTIME_DIR="/tmp/runtime-zaza",LANG="fr_FR.UTF-8"
command=/bin/sh -c "sleep 2; exec /usr/bin/startxfce4"
user=zaza
priority=500
autorestart=true
stdout_logfile=/var/log/desk/xfce.log
redirect_stderr=true

[program:x11vnc]
command=/bin/sh -c "sleep 4; exec /usr/bin/x11vnc -display :99 -forever -shared -nopw -rfbport 5900 -localhost"
priority=600
autorestart=true
stdout_logfile=/var/log/desk/x11vnc.log
redirect_stderr=true

[program:novnc]
command=/usr/share/novnc/utils/novnc_proxy --vnc localhost:5900 --listen 6080
priority=700
autorestart=true
stdout_logfile=/var/log/desk/novnc.log
redirect_stderr=true

[program:sshd]
command=/usr/sbin/sshd -D
priority=200
autorestart=true
